name: miniz
description: A dart port of Miniz compression library.
version: 1.0.0
homepage: https://github.com/joistaus/flutter_miniz
repository: https://github.com/joistaus/flutter_miniz
topics:
    - compression
    - miniz
    - zlib

platforms:
    windows:
    macos:
    linux:
    ios:
    android:

environment:
    sdk: ">=3.1.2 <4.0.0"
    flutter: ">=3.3.0"

dependencies:
    ffi: ^2.1.0
    flutter:
        sdk: flutter
    path: ^1.8.3
    plugin_platform_interface: ^2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    plugin:
        platforms:
            android:
                ffiPlugin: true
            ios:
                ffiPlugin: true
            linux:
                ffiPlugin: true
            macos:
                ffiPlugin: true
            windows:
                ffiPlugin: true
